import { Container } from '@chakra-ui/react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import EmblaCarousel from './components/emblaCarousel'
import Shopmenu from './components/shopmenu'

export default function Home() {
  return (
    <>
      {<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>}

      <Container padding={0} margin={'auto'} maxW={1200}>
        <EmblaCarousel />
        
        <Shopmenu />
        
        
      </Container>


    </>
  )
}
