import { Container } from '@chakra-ui/react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import EmblaCarousel from './components/emblaCarousel'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container minH='80vh' maxW={ 1200}>

        <EmblaCarousel/>
      </Container>
    </div>
  )
}
